# Code generated by scripts/generate_browser_scoped.py. DO NOT EDIT.
# ruff: noqa: I001, F401
# pyright: reportUnusedImport=false
# mypy: ignore-errors
"""Browser-scoped wrappers over generated `resources.browsers` classes (AST-driven)."""

from __future__ import annotations

from typing import Any

from ..._compat import cached_property
from .util import ScopedResourceProxy

from typing import Iterable
from typing_extensions import Literal
import httpx
from kernel._types import Body, Omit, Query, Headers, NoneType, NotGiven, SequenceNotStr, omit, not_given
from kernel._response import (
    BinaryAPIResponse,
    AsyncBinaryAPIResponse,
    StreamedBinaryAPIResponse,
    AsyncStreamedBinaryAPIResponse,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
    async_to_raw_response_wrapper,
    to_custom_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_custom_streamed_response_wrapper,
    async_to_custom_raw_response_wrapper,
    async_to_custom_streamed_response_wrapper,
)
from kernel.types.browsers import (
    computer_batch_params,
    computer_scroll_params,
    computer_press_key_params,
    computer_type_text_params,
    computer_drag_mouse_params,
    computer_move_mouse_params,
    computer_click_mouse_params,
    computer_write_clipboard_params,
    computer_capture_screenshot_params,
    computer_set_cursor_visibility_params,
)
from kernel.types.browsers.computer_read_clipboard_response import ComputerReadClipboardResponse
from kernel.types.browsers.computer_get_mouse_position_response import ComputerGetMousePositionResponse
from kernel.types.browsers.computer_set_cursor_visibility_response import ComputerSetCursorVisibilityResponse
import os
from typing import Mapping, Iterable, cast
from kernel.resources.browsers.fs.watch import (
    WatchResource,
    AsyncWatchResource,
    WatchResourceWithRawResponse,
    AsyncWatchResourceWithRawResponse,
    WatchResourceWithStreamingResponse,
    AsyncWatchResourceWithStreamingResponse,
)
from kernel._files import read_file_content, async_read_file_content
from kernel._types import (
    Body,
    Omit,
    Query,
    Headers,
    NoneType,
    NotGiven,
    FileTypes,
    BinaryTypes,
    FileContent,
    AsyncBinaryTypes,
    omit,
    not_given,
)
from kernel.types.browsers import (
    f_move_params,
    f_upload_params,
    f_file_info_params,
    f_read_file_params,
    f_list_files_params,
    f_upload_zip_params,
    f_write_file_params,
    f_delete_file_params,
    f_create_directory_params,
    f_delete_directory_params,
    f_download_dir_zip_params,
    f_set_file_permissions_params,
)
from kernel.types.browsers.f_file_info_response import FFileInfoResponse
from kernel.types.browsers.f_list_files_response import FListFilesResponse
from kernel._types import Body, Omit, Query, Headers, NoneType, NotGiven, omit, not_given
from kernel._response import (
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
)
from kernel._streaming import Stream, AsyncStream
from kernel.types.browsers.fs import watch_start_params
from kernel.types.browsers.fs.watch_start_response import WatchStartResponse
from kernel.types.browsers.fs.watch_events_response import WatchEventsResponse
from kernel._types import Body, Omit, Query, Headers, NotGiven, omit, not_given
from kernel.types.browsers import log_stream_params
from kernel.types.shared.log_event import LogEvent
from kernel.types.browsers import playwright_execute_params
from kernel.types.browsers.playwright_execute_response import PlaywrightExecuteResponse
from typing import Dict, Optional
from kernel._types import Body, Omit, Query, Headers, NotGiven, SequenceNotStr, omit, not_given
from kernel.types.browsers import (
    process_exec_params,
    process_kill_params,
    process_spawn_params,
    process_stdin_params,
    process_resize_params,
)
from kernel.types.browsers.process_exec_response import ProcessExecResponse
from kernel.types.browsers.process_kill_response import ProcessKillResponse
from kernel.types.browsers.process_spawn_response import ProcessSpawnResponse
from kernel.types.browsers.process_stdin_response import ProcessStdinResponse
from kernel.types.browsers.process_resize_response import ProcessResizeResponse
from kernel.types.browsers.process_status_response import ProcessStatusResponse
from kernel.types.browsers.process_stdout_stream_response import ProcessStdoutStreamResponse
from kernel.types.browsers import replay_start_params
from kernel.types.browsers.replay_list_response import ReplayListResponse
from kernel.types.browsers.replay_start_response import ReplayStartResponse


class BoundComputerResource(ScopedResourceProxy):
    """Session id is injected for browser API methods."""

    def batch(
        self,
        *,
        actions: Iterable[computer_batch_params.Action],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.batch(
            self._session_id,
            actions=actions,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def capture_screenshot(
        self,
        *,
        region: computer_capture_screenshot_params.Region | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> BinaryAPIResponse:
        return self._inner.capture_screenshot(
            self._session_id,
            region=region,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def click_mouse(
        self,
        *,
        x: int,
        y: int,
        button: Literal["left", "right", "middle", "back", "forward"] | Omit = omit,
        click_type: Literal["down", "up", "click"] | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        num_clicks: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.click_mouse(
            self._session_id,
            x=x,
            y=y,
            button=button,
            click_type=click_type,
            hold_keys=hold_keys,
            num_clicks=num_clicks,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def drag_mouse(
        self,
        *,
        path: Iterable[Iterable[int]],
        button: Literal["left", "middle", "right"] | Omit = omit,
        delay: int | Omit = omit,
        duration_ms: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        smooth: bool | Omit = omit,
        step_delay_ms: int | Omit = omit,
        steps_per_segment: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.drag_mouse(
            self._session_id,
            path=path,
            button=button,
            delay=delay,
            duration_ms=duration_ms,
            hold_keys=hold_keys,
            smooth=smooth,
            step_delay_ms=step_delay_ms,
            steps_per_segment=steps_per_segment,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def get_mouse_position(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ComputerGetMousePositionResponse:
        return self._inner.get_mouse_position(
            self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def move_mouse(
        self,
        *,
        x: int,
        y: int,
        duration_ms: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        smooth: bool | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.move_mouse(
            self._session_id,
            x=x,
            y=y,
            duration_ms=duration_ms,
            hold_keys=hold_keys,
            smooth=smooth,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def press_key(
        self,
        *,
        keys: SequenceNotStr[str],
        duration: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.press_key(
            self._session_id,
            keys=keys,
            duration=duration,
            hold_keys=hold_keys,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def read_clipboard(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ComputerReadClipboardResponse:
        return self._inner.read_clipboard(
            self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def scroll(
        self,
        *,
        x: int,
        y: int,
        delta_x: int | Omit = omit,
        delta_y: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.scroll(
            self._session_id,
            x=x,
            y=y,
            delta_x=delta_x,
            delta_y=delta_y,
            hold_keys=hold_keys,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def set_cursor_visibility(
        self,
        *,
        hidden: bool,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ComputerSetCursorVisibilityResponse:
        return self._inner.set_cursor_visibility(
            self._session_id,
            hidden=hidden,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def type_text(
        self,
        *,
        text: str,
        delay: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.type_text(
            self._session_id,
            text=text,
            delay=delay,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def write_clipboard(
        self,
        *,
        text: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.write_clipboard(
            self._session_id,
            text=text,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundAsyncComputerResource(ScopedResourceProxy):
    """Async variant: session id is injected for browser API methods."""

    async def batch(
        self,
        *,
        actions: Iterable[computer_batch_params.Action],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.batch(
            self._session_id,
            actions=actions,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def capture_screenshot(
        self,
        *,
        region: computer_capture_screenshot_params.Region | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncBinaryAPIResponse:
        return await self._inner.capture_screenshot(
            self._session_id,
            region=region,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def click_mouse(
        self,
        *,
        x: int,
        y: int,
        button: Literal["left", "right", "middle", "back", "forward"] | Omit = omit,
        click_type: Literal["down", "up", "click"] | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        num_clicks: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.click_mouse(
            self._session_id,
            x=x,
            y=y,
            button=button,
            click_type=click_type,
            hold_keys=hold_keys,
            num_clicks=num_clicks,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def drag_mouse(
        self,
        *,
        path: Iterable[Iterable[int]],
        button: Literal["left", "middle", "right"] | Omit = omit,
        delay: int | Omit = omit,
        duration_ms: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        smooth: bool | Omit = omit,
        step_delay_ms: int | Omit = omit,
        steps_per_segment: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.drag_mouse(
            self._session_id,
            path=path,
            button=button,
            delay=delay,
            duration_ms=duration_ms,
            hold_keys=hold_keys,
            smooth=smooth,
            step_delay_ms=step_delay_ms,
            steps_per_segment=steps_per_segment,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def get_mouse_position(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ComputerGetMousePositionResponse:
        return await self._inner.get_mouse_position(
            self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def move_mouse(
        self,
        *,
        x: int,
        y: int,
        duration_ms: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        smooth: bool | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.move_mouse(
            self._session_id,
            x=x,
            y=y,
            duration_ms=duration_ms,
            hold_keys=hold_keys,
            smooth=smooth,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def press_key(
        self,
        *,
        keys: SequenceNotStr[str],
        duration: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.press_key(
            self._session_id,
            keys=keys,
            duration=duration,
            hold_keys=hold_keys,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def read_clipboard(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ComputerReadClipboardResponse:
        return await self._inner.read_clipboard(
            self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def scroll(
        self,
        *,
        x: int,
        y: int,
        delta_x: int | Omit = omit,
        delta_y: int | Omit = omit,
        hold_keys: SequenceNotStr[str] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.scroll(
            self._session_id,
            x=x,
            y=y,
            delta_x=delta_x,
            delta_y=delta_y,
            hold_keys=hold_keys,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def set_cursor_visibility(
        self,
        *,
        hidden: bool,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ComputerSetCursorVisibilityResponse:
        return await self._inner.set_cursor_visibility(
            self._session_id,
            hidden=hidden,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def type_text(
        self,
        *,
        text: str,
        delay: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.type_text(
            self._session_id,
            text=text,
            delay=delay,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def write_clipboard(
        self,
        *,
        text: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.write_clipboard(
            self._session_id,
            text=text,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundLogsResource(ScopedResourceProxy):
    """Session id is injected for browser API methods."""

    def stream(
        self,
        *,
        source: Literal["path", "supervisor"],
        follow: bool | Omit = omit,
        path: str | Omit = omit,
        supervisor_process: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Stream[LogEvent]:
        return self._inner.stream(
            self._session_id,
            source=source,
            follow=follow,
            path=path,
            supervisor_process=supervisor_process,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundAsyncLogsResource(ScopedResourceProxy):
    """Async variant: session id is injected for browser API methods."""

    async def stream(
        self,
        *,
        source: Literal["path", "supervisor"],
        follow: bool | Omit = omit,
        path: str | Omit = omit,
        supervisor_process: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncStream[LogEvent]:
        return await self._inner.stream(
            self._session_id,
            source=source,
            follow=follow,
            path=path,
            supervisor_process=supervisor_process,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundPlaywrightResource(ScopedResourceProxy):
    """Session id is injected for browser API methods."""

    def execute(
        self,
        *,
        code: str,
        timeout_sec: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> PlaywrightExecuteResponse:
        return self._inner.execute(
            self._session_id,
            code=code,
            timeout_sec=timeout_sec,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundAsyncPlaywrightResource(ScopedResourceProxy):
    """Async variant: session id is injected for browser API methods."""

    async def execute(
        self,
        *,
        code: str,
        timeout_sec: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> PlaywrightExecuteResponse:
        return await self._inner.execute(
            self._session_id,
            code=code,
            timeout_sec=timeout_sec,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundProcessResource(ScopedResourceProxy):
    """Session id is injected for browser API methods."""

    def exec(
        self,
        *,
        command: str,
        args: SequenceNotStr[str] | Omit = omit,
        as_root: bool | Omit = omit,
        as_user: Optional[str] | Omit = omit,
        cwd: Optional[str] | Omit = omit,
        env: Dict[str, str] | Omit = omit,
        timeout_sec: Optional[int] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessExecResponse:
        return self._inner.exec(
            self._session_id,
            command=command,
            args=args,
            as_root=as_root,
            as_user=as_user,
            cwd=cwd,
            env=env,
            timeout_sec=timeout_sec,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def kill(
        self,
        process_id: str,
        *,
        signal: Literal["TERM", "KILL", "INT", "HUP"],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessKillResponse:
        return self._inner.kill(
            process_id,
            id=self._session_id,
            signal=signal,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def resize(
        self,
        process_id: str,
        *,
        cols: int,
        rows: int,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessResizeResponse:
        return self._inner.resize(
            process_id,
            id=self._session_id,
            cols=cols,
            rows=rows,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def spawn(
        self,
        *,
        command: str,
        allocate_tty: bool | Omit = omit,
        args: SequenceNotStr[str] | Omit = omit,
        as_root: bool | Omit = omit,
        as_user: Optional[str] | Omit = omit,
        cols: int | Omit = omit,
        cwd: Optional[str] | Omit = omit,
        env: Dict[str, str] | Omit = omit,
        rows: int | Omit = omit,
        timeout_sec: Optional[int] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessSpawnResponse:
        return self._inner.spawn(
            self._session_id,
            command=command,
            allocate_tty=allocate_tty,
            args=args,
            as_root=as_root,
            as_user=as_user,
            cols=cols,
            cwd=cwd,
            env=env,
            rows=rows,
            timeout_sec=timeout_sec,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def status(
        self,
        process_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessStatusResponse:
        return self._inner.status(
            process_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def stdin(
        self,
        process_id: str,
        *,
        data_b64: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessStdinResponse:
        return self._inner.stdin(
            process_id,
            id=self._session_id,
            data_b64=data_b64,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def stdout_stream(
        self,
        process_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Stream[ProcessStdoutStreamResponse]:
        return self._inner.stdout_stream(
            process_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundAsyncProcessResource(ScopedResourceProxy):
    """Async variant: session id is injected for browser API methods."""

    async def exec(
        self,
        *,
        command: str,
        args: SequenceNotStr[str] | Omit = omit,
        as_root: bool | Omit = omit,
        as_user: Optional[str] | Omit = omit,
        cwd: Optional[str] | Omit = omit,
        env: Dict[str, str] | Omit = omit,
        timeout_sec: Optional[int] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessExecResponse:
        return await self._inner.exec(
            self._session_id,
            command=command,
            args=args,
            as_root=as_root,
            as_user=as_user,
            cwd=cwd,
            env=env,
            timeout_sec=timeout_sec,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def kill(
        self,
        process_id: str,
        *,
        signal: Literal["TERM", "KILL", "INT", "HUP"],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessKillResponse:
        return await self._inner.kill(
            process_id,
            id=self._session_id,
            signal=signal,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def resize(
        self,
        process_id: str,
        *,
        cols: int,
        rows: int,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessResizeResponse:
        return await self._inner.resize(
            process_id,
            id=self._session_id,
            cols=cols,
            rows=rows,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def spawn(
        self,
        *,
        command: str,
        allocate_tty: bool | Omit = omit,
        args: SequenceNotStr[str] | Omit = omit,
        as_root: bool | Omit = omit,
        as_user: Optional[str] | Omit = omit,
        cols: int | Omit = omit,
        cwd: Optional[str] | Omit = omit,
        env: Dict[str, str] | Omit = omit,
        rows: int | Omit = omit,
        timeout_sec: Optional[int] | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessSpawnResponse:
        return await self._inner.spawn(
            self._session_id,
            command=command,
            allocate_tty=allocate_tty,
            args=args,
            as_root=as_root,
            as_user=as_user,
            cols=cols,
            cwd=cwd,
            env=env,
            rows=rows,
            timeout_sec=timeout_sec,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def status(
        self,
        process_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessStatusResponse:
        return await self._inner.status(
            process_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def stdin(
        self,
        process_id: str,
        *,
        data_b64: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ProcessStdinResponse:
        return await self._inner.stdin(
            process_id,
            id=self._session_id,
            data_b64=data_b64,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def stdout_stream(
        self,
        process_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncStream[ProcessStdoutStreamResponse]:
        return await self._inner.stdout_stream(
            process_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundReplaysResource(ScopedResourceProxy):
    """Session id is injected for browser API methods."""

    def list(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ReplayListResponse:
        return self._inner.list(
            self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def download(
        self,
        replay_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> BinaryAPIResponse:
        return self._inner.download(
            replay_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def start(
        self,
        *,
        framerate: int | Omit = omit,
        max_duration_in_seconds: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ReplayStartResponse:
        return self._inner.start(
            self._session_id,
            framerate=framerate,
            max_duration_in_seconds=max_duration_in_seconds,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def stop(
        self,
        replay_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.stop(
            replay_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundAsyncReplaysResource(ScopedResourceProxy):
    """Async variant: session id is injected for browser API methods."""

    async def list(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ReplayListResponse:
        return await self._inner.list(
            self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def download(
        self,
        replay_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncBinaryAPIResponse:
        return await self._inner.download(
            replay_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def start(
        self,
        *,
        framerate: int | Omit = omit,
        max_duration_in_seconds: int | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ReplayStartResponse:
        return await self._inner.start(
            self._session_id,
            framerate=framerate,
            max_duration_in_seconds=max_duration_in_seconds,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def stop(
        self,
        replay_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.stop(
            replay_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundWatchResource(ScopedResourceProxy):
    """Session id is injected for browser API methods."""

    def events(
        self,
        watch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Stream[WatchEventsResponse]:
        return self._inner.events(
            watch_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def start(
        self,
        *,
        path: str,
        recursive: bool | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> WatchStartResponse:
        return self._inner.start(
            self._session_id,
            path=path,
            recursive=recursive,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def stop(
        self,
        watch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.stop(
            watch_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundAsyncWatchResource(ScopedResourceProxy):
    """Async variant: session id is injected for browser API methods."""

    async def events(
        self,
        watch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncStream[WatchEventsResponse]:
        return await self._inner.events(
            watch_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def start(
        self,
        *,
        path: str,
        recursive: bool | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> WatchStartResponse:
        return await self._inner.start(
            self._session_id,
            path=path,
            recursive=recursive,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def stop(
        self,
        watch_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.stop(
            watch_id,
            id=self._session_id,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundFsResource(ScopedResourceProxy):
    """Session id is injected for browser API methods."""

    @cached_property
    def watch(self) -> BoundWatchResource:
        from ...resources.browsers.fs.watch import WatchResource

        return BoundWatchResource(WatchResource(self._inner._client), self._session_id)

    def create_directory(
        self,
        *,
        path: str,
        mode: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.create_directory(
            self._session_id,
            path=path,
            mode=mode,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def delete_directory(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.delete_directory(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def delete_file(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.delete_file(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def download_dir_zip(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> BinaryAPIResponse:
        return self._inner.download_dir_zip(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def file_info(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> FFileInfoResponse:
        return self._inner.file_info(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def list_files(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> FListFilesResponse:
        return self._inner.list_files(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def move(
        self,
        *,
        dest_path: str,
        src_path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.move(
            self._session_id,
            dest_path=dest_path,
            src_path=src_path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def read_file(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> BinaryAPIResponse:
        return self._inner.read_file(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def set_file_permissions(
        self,
        *,
        mode: str,
        path: str,
        group: str | Omit = omit,
        owner: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.set_file_permissions(
            self._session_id,
            mode=mode,
            path=path,
            group=group,
            owner=owner,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def upload(
        self,
        *,
        files: Iterable[f_upload_params.File],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.upload(
            self._session_id,
            files=files,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def upload_zip(
        self,
        *,
        dest_path: str,
        zip_file: FileTypes,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.upload_zip(
            self._session_id,
            dest_path=dest_path,
            zip_file=zip_file,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    def write_file(
        self,
        contents: FileContent | BinaryTypes,
        *,
        path: str,
        mode: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return self._inner.write_file(
            self._session_id,
            contents,
            path=path,
            mode=mode,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BoundAsyncFsResource(ScopedResourceProxy):
    """Async variant: session id is injected for browser API methods."""

    @cached_property
    def watch(self) -> BoundAsyncWatchResource:
        from ...resources.browsers.fs.watch import AsyncWatchResource

        return BoundAsyncWatchResource(AsyncWatchResource(self._inner._client), self._session_id)

    async def create_directory(
        self,
        *,
        path: str,
        mode: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.create_directory(
            self._session_id,
            path=path,
            mode=mode,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def delete_directory(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.delete_directory(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def delete_file(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.delete_file(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def download_dir_zip(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncBinaryAPIResponse:
        return await self._inner.download_dir_zip(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def file_info(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> FFileInfoResponse:
        return await self._inner.file_info(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def list_files(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> FListFilesResponse:
        return await self._inner.list_files(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def move(
        self,
        *,
        dest_path: str,
        src_path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.move(
            self._session_id,
            dest_path=dest_path,
            src_path=src_path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def read_file(
        self,
        *,
        path: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncBinaryAPIResponse:
        return await self._inner.read_file(
            self._session_id,
            path=path,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def set_file_permissions(
        self,
        *,
        mode: str,
        path: str,
        group: str | Omit = omit,
        owner: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.set_file_permissions(
            self._session_id,
            mode=mode,
            path=path,
            group=group,
            owner=owner,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def upload(
        self,
        *,
        files: Iterable[f_upload_params.File],
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.upload(
            self._session_id,
            files=files,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def upload_zip(
        self,
        *,
        dest_path: str,
        zip_file: FileTypes,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.upload_zip(
            self._session_id,
            dest_path=dest_path,
            zip_file=zip_file,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )

    async def write_file(
        self,
        contents: FileContent | AsyncBinaryTypes,
        *,
        path: str,
        mode: str | Omit = omit,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> None:
        return await self._inner.write_file(
            self._session_id,
            contents,
            path=path,
            mode=mode,
            extra_headers=extra_headers,
            extra_query=extra_query,
            extra_body=extra_body,
            timeout=timeout,
        )


class BrowserScopedFacadeMixin:
    """Top-level browser session subresources (sync); uses `_http` and `session_id`."""

    _http: Any
    session_id: str

    @cached_property
    def computer(self) -> BoundComputerResource:
        from ...resources.browsers.computer import ComputerResource

        return BoundComputerResource(ComputerResource(self._http), self.session_id)

    @cached_property
    def fs(self) -> BoundFsResource:
        from ...resources.browsers.fs.fs import FsResource

        return BoundFsResource(FsResource(self._http), self.session_id)

    @cached_property
    def logs(self) -> BoundLogsResource:
        from ...resources.browsers.logs import LogsResource

        return BoundLogsResource(LogsResource(self._http), self.session_id)

    @cached_property
    def playwright(self) -> BoundPlaywrightResource:
        from ...resources.browsers.playwright import PlaywrightResource

        return BoundPlaywrightResource(PlaywrightResource(self._http), self.session_id)

    @cached_property
    def process(self) -> BoundProcessResource:
        from ...resources.browsers.process import ProcessResource

        return BoundProcessResource(ProcessResource(self._http), self.session_id)

    @cached_property
    def replays(self) -> BoundReplaysResource:
        from ...resources.browsers.replays import ReplaysResource

        return BoundReplaysResource(ReplaysResource(self._http), self.session_id)


class AsyncBrowserScopedFacadeMixin:
    """Top-level browser session subresources (async); uses `_http` and `session_id`."""

    _http: Any
    session_id: str

    @cached_property
    def computer(self) -> BoundAsyncComputerResource:
        from ...resources.browsers.computer import AsyncComputerResource

        return BoundAsyncComputerResource(AsyncComputerResource(self._http), self.session_id)

    @cached_property
    def fs(self) -> BoundAsyncFsResource:
        from ...resources.browsers.fs.fs import AsyncFsResource

        return BoundAsyncFsResource(AsyncFsResource(self._http), self.session_id)

    @cached_property
    def logs(self) -> BoundAsyncLogsResource:
        from ...resources.browsers.logs import AsyncLogsResource

        return BoundAsyncLogsResource(AsyncLogsResource(self._http), self.session_id)

    @cached_property
    def playwright(self) -> BoundAsyncPlaywrightResource:
        from ...resources.browsers.playwright import AsyncPlaywrightResource

        return BoundAsyncPlaywrightResource(AsyncPlaywrightResource(self._http), self.session_id)

    @cached_property
    def process(self) -> BoundAsyncProcessResource:
        from ...resources.browsers.process import AsyncProcessResource

        return BoundAsyncProcessResource(AsyncProcessResource(self._http), self.session_id)

    @cached_property
    def replays(self) -> BoundAsyncReplaysResource:
        from ...resources.browsers.replays import AsyncReplaysResource

        return BoundAsyncReplaysResource(AsyncReplaysResource(self._http), self.session_id)


__all__ = [
    "BoundAsyncComputerResource",
    "BoundAsyncFsResource",
    "BoundAsyncLogsResource",
    "BoundAsyncPlaywrightResource",
    "BoundAsyncProcessResource",
    "BoundAsyncReplaysResource",
    "BoundAsyncWatchResource",
    "BoundComputerResource",
    "BoundFsResource",
    "BoundLogsResource",
    "BoundPlaywrightResource",
    "BoundProcessResource",
    "BoundReplaysResource",
    "BoundWatchResource",
]
